### ISSUE TITLE
Visualizar Home del E-commerce

### ISSUE THREAD

**Issue by MariRoLo** [Grupo-9-Anita/e-commerce-tpi-frontend#31]
Como cliente, quiero acceder a la página principal (Home) del ecommerce, para visualizar los productos destacados, promociones, categorías principales y novedades de forma rápida y sencilla.

Criterios de aceptación:

- [x] El sistema debe mostrar al cliente los productos que la empresa ofrece incluyendo: nombre, stock disponible, precio, imagen (opcional).
- [x] De haberse registrado un producto sin imagen, el sistema debe mostrar una imagen predeterminada "No Image" en su lugar.
- [x] Deshabilitar la opcion de comprar el producto si no tiene stock disponible.
- [x] El cliente podrá agregar productos al carrito de compras desde el home, únicamente si éstos cuentan con stock disponible

**Comment by JaaF97** [comment]
Acordate de agregar los cambios que realizamos!!!

### Criterios de aceptación
- **Agregados:**
    - El cliente podrá agregar productos al carrito de compras desde el home, únicamente si éstos cuentan con stock disponible.
- **Modificados:**
    - El sistema debe mostrar al cliente los productos que la empresa ofrece incluyendo: nombre, descripción, stock disponible, precio, imagen ~~(opcional)~~.
- **Eliminados:**
    - De haberse registrado un producto sin imagen, el sistema debe mostrar una imagen predeterminada "No Image" en su lugar.
    - Deshabilitar la opcion de comprar el producto si no tiene stock disponible.
